[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true

[project]
name = "b3_bem"
version = "0.1.1"
authors = [{name = "wr1", email = "8971152+wr1@users.noreply.github.com"}]
dependencies = [
    "numpy",
    "pandas",
    "matplotlib",
    "scipy",
    "CCBlade @ git+https://github.com/WISDEM/CCBlade.git@master", 
    # "CCBlade",
    # "ccblade @ file:///home/wr1/projects/CCBlade",
    "rich",
    # "statesman",
    "treeparse",
    "ruamel.yaml",
    "pydantic",
    "pytest",
]

[project.scripts]
"b3-bem" = "b3_bem.cli.cli:main"

[tool.pytest.ini_options]
addopts = "--cov=src/b3_bem --cov-report=term"